/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'waszka' at '19/10/16 21:44' with Gradle 3.0
 *
 * @author waszka, @date 19/10/16 21:44
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
